### ISSUE TITLE
Update database

### ISSUE THREAD

**Issue by nkyo** [DemonRem/UltimateBNS#1]
Hi DemonRem,
Can you update latest database of Blade And Soul Korea, thank.

**Comment by DemonRem** [comment]
tomorrow i will be update the database

**Comment by DemonRem** [comment]
@nkyo I download the Korean server to my pc right now and i will add a feature , select server location to for access to few version of the game

**Comment by nkyo** [comment]
thank you xD

**Comment by nkyo** [comment]
waiting for your new database xD
