### ISSUE TITLE
Database Update

### ISSUE THREAD

**Issue by DemonRem** [DemonRem/UltimateBNS#2]
Adding Items to c#
remove the json files and add tool ability to handle game data

**Comment by nkyo** [comment]
great work!

**Comment by nkyo** [comment]
I don't know how to download korea  BnS game, so sad

**Comment by nkyo** [comment]
> Adding Items to c#
> remove the json files and add tool ability to handle game data

con download failed: https://github.com/DemonRem/bnsdatabasemaster/database/icon/png-cps/Costume_60007_JinM_col4.png
Icon download failed: https://github.com/DemonRem/bnsdatabasemaster/database/icon/png-cps/Costume_60005_JinM_col1.png

https://github.com/DemonRem/bnsdatabase are you updating xD

**Comment by DemonRem** [comment]
yea It's updated it's internet issue I belive it's show on the GitHub tomorrow,
i take the time to wait for this update , to preform full database update i sorry for the delay

**Comment by DemonRem** [comment]
@nkyo 

you may track the project progress in the board neither : https://github.com/DemonRem/UltimateBNS/projects/1

**Comment by nkyo** [comment]
> @nkyo
> 
> you may track the project progress in the board neither : https://github.com/DemonRem/UltimateBNS/projects/1

thank you.

**Comment by DemonRem** [comment]
@nkyo 
database ready any will be avilable in suppsed closed to 1 hour , please let me know if  there is an issue with the tool
