### ISSUE TITLE
BnS KR database Pointer

### ISSUE THREAD

**Issue by nkyo** [DemonRem/UltimateBNS#3]
I just use database tool to update from BNS KR, https://github.com/nkyo/BnsKR_database

**Comment by DemonRem** [comment]
@nkyo there a bug where you used in you git , I will point the korea category to get from your git the data while my is the western region keep tune on the tool changes, anyway the git must have 3 directory of the database not a single one it's supposed to be like that 
in the root folder , sould be 
Custome
Icon
Attach ,
make sure you put the a folder in each of those folder called "pics-cps" put there the images from this directory output by the database updater on that done please let me know.

**Comment by nkyo** [comment]
@DemonRem I think there's an error with exe in \VS_GUI\BladeSoulTool\bin\Debug\BladeSoulTool.exe

**Comment by DemonRem** [comment]
I know there is an issue I check it

**Comment by DemonRem** [comment]
#solved

the tool work again
